### ISSUE TITLE
Stats: Tables: View interfaces

### ISSUE THREAD

**Issue by kamsi** [egovernment/eregistrations#1759]
https://github.com/egovernment/eregistrations/issues/1756

This is about preparing views and controllers for the new statistics: https://docs.google.com/document/d/1i92UhTr_krhLYVc9TA88WGIrvwPAnM9x84WHCFpVtQc/edit

The data will be handled separately here: https://github.com/egovernment/eregistrations/issues/1758

**Comment by medikoo** [comment]
@vianneyl do views as presented here: http://xwv4ez.axshare.com/#p=table_of_quantities_of_files_in_status__per_certif
are final (?)

I think there were some changes to them agreed, it'll be great to have them updated.

**Comment by vianneyl** [comment]
@medikoo yes they are final

2017-01-26 16:08 GMT+01:00 Mariusz Nowak <notifications@github.com>:

**Comment by medikoo** [comment]
@vianneyl some clarifications

__All tables__

As in case of some other statistics pages, we will operate only on data gathered after some point in time. Therefore we should gently inform user about with it message as:
_As history of status changes is properly recorded since 1st of February 2017, below table only exposes data for files processed after that day_.
I take that we should follow what was proposed here: #1727 and put that info into (i) tooltip by period selector.

__Table 1 & Table 2__

It's not shown on view, but I take we will paginate results to not show more than 100 rows per page (paginator will only show if we have more than 100 items)

__Table 3__

- Here pagination is not straighforward, e.g. for first table we may have 10000 results and in other 100 results, it's not clear how to deal with pagination here.
I take that each table should be paginated individually, but then it becomes more challenging to reflect that in url address bar (which should be in place if we want to have that page working properly in all supported browsers). I propose that we should introduce query names as `revisionPage`, `precalPage` etc.
-  I understand that we show only those operators which have some processing history at given day. So there can be scenarios where not only some processors will appear from time to time, but some days may not appear at all.
- In case where either "Sent back.." or "Rejected" do not apply to given step we do not show this column (alternative way is to show "N/A" in them, but I think it's unnecessary noise)

@vianneyl please confirm is all that ok, or elaborate if you have other ideas

Additionally it's not clear how to prepare CSV export for Table 3, can you prepare some proposal?

**Comment by medikoo** [comment]
@vianneyl  other question, in spec you write:

```
The lines of the table are: 
- days included in the period selector  if “Daily” is selected
- weeks included in the selected period if “weekly” is selected
- months included in the selected period if “Monthly” is selected
- years included in the selected period if “Yearly” is selected
```

Do you expect the period selector to not only allow select range with _day_ granularity, but also with _week_, _month_ and _year_ granularity? 

To precise via question: What interface do you expect in period selector when "Yearly" is selected?
- The normal calendar (so one can select incomplete year range, e.g. starting from October)
- Control allowing to select range of years (e.g. 2012-2016). Mind that we don't have any component for that, and I think it might not be that straightforward to configure one.

**Comment by vianneyl** [comment]
@medikoo 

1. *All tables* 
It is not possible to have the data from before February 1st? I think that we already have a lot of data available and we could find it somehow. This is important as already many things happen in our systems. 

2. *It's not shown on view, but I take we will paginate results to not show more than 100 rows per page.*
Yes ok, but only if this take quite no time.

3. *I take that each table should be paginated individually*
This seems very difficult, I hope it will not take any more time.

4.* I understand that we show only those operators which have some processing history at given day.*
No, we can also show when the data is 0, so we have the raw-data.

5. *In case where either "Sent back.." or "Rejected" do not apply to given step we do not show this column*
Indeed, that would be nice. 
If difficult, yes let's go for the n/a solution.

6. The period selector would be the same as in Medhi system, the same we talk about here: https://github.com/egovernment/eregistrations/pull/1496

So to select 2012-2016, I will have to go to the custom dates and select 01-01-2012 and 31-12-2016.

I do not understand the rest of the questions, but:
- Yearly will display lines as years
- Monthly will display lines as month
- Weekly will display lines as week
- Days will display lines as days

**Comment by medikoo** [comment]
> It is not possible to have the data from before February 1st? I think that we already have a lot of data available and we could find it somehow. This is important as already many things happen in our systems.

Before the date the #1757 will be published, we will have just fraction of information. @kamsi indicated to me that it was clarified for you.

Technically we can show older dates, but over there we will have just following information:
- __Table 1__ -  "Submitted", "Withdrawn By User" and "Rejected" columns, for other columns we can then show N/A
- __Table 2__ - Just data for statuses "Rejected" and "Validated", in other cases table will have whole table filled with N/A values
- __Table 3__ - No data for "Sent back for corrections" we will have to show N/A there

We can then show by `N/A` listings the hint I proposed. Let me know if you want to do that.
Also mind that handling of old data will increase development time.

> _4. I understand that we show only those operators which have some processing history at given day._
> No, we can also show when the data is 0, so we have the raw-data.

If I understand right you want to have listed all operators registered currently and show them through out all the history (?)
This is controversial, as operators also come and go, e.g. imagine situation that in "January 2015" for given step there were assigned operators `A` and `B`, while today assigned operators are `B` and `C`.
If we follow this idea, then for "January 2015" we will list `B` and `C`, it leads to false information as:
- `C` would be listed with `0` while at given date it was not then even registered in a system
- `A` would not be listed although he may have processed 10 files at that date.

Ideal solution would be to track per day what were the assigned operators for given role, but that will incur additional work. That's why I thought that the quickest solution would be to just show the operators that we know by their actions that were registered and worked on that day.

> So to select 2012-2016, I will have to go to the custom dates and select 01-01-2012 and 31-12-2016.

Ok, I assume that you expect the range selector with _date_ granularity at all times, even if "Weekly", "Monthly" or "Yearly" views are selected.

It means that e.g. user will be capable to select "Yearly", and then in period selector select range of "2016-05-02" and "2016-07-12".
@kamsi informed me that in such scenario the agreement is to in "2016" row show the numbers resolved _strictly_ from selected period (so in case of that example, data in "2016" row will reflect the part of may until mid of July) and not whole year. Please confirm, that's the intention.

We can also add an extra adjustment, so if someone will switches to "Yearly" we update range in period selector to express full years, still that won't prevent the user from changing that range after to one that covers just fraction of years.

**Comment by vianneyl** [comment]
@medikoo 

1. yes we need to be able to retrieve the old information, even if some data will be missing. 
OK, for those missing data, to write n/a with the tooltip you suggested. 

2. ok, my mistake, you were right, we show "only those operators which have some processing history at given day".

3. the range selector is indeed always with date granularity, the choice of "Yearly, Monthly, Weekly, Daily" is just the way the system displays the lines..
Example is if I select the dates 01/01/2016 and 30/06/2016 and set the "Yearly" display, then the table will be one line showing "2016" and the data will be the ones of all the days between 01/01 and 30/06.
So yes, I confirm :)

> We can also add an extra adjustment, so if someone will switches to "Yearly" we update range in period selector to express full years, still that won't prevent the user from changing that range after to one that covers just fraction of years.

We could do that, but this is fine-tuning, let's keep this idea for later. Thank you for proposing it!

**Comment by medikoo** [comment]
Thanks @vianneyl nearly all is clear.

One last question, you expect as to provide CSV export for each page, While last one presents many tables, and as far as I understand CSV export it can only be about one table.
Therefore either explain how do you expect to represent all tables in one CSV table, or I suggest to present "Export as CSV" buttons by each of a table, and not in top filter.

**Comment by vianneyl** [comment]
@medikoo for last one, the role is the first column, which make possible to have 1 table.

**Comment by medikoo** [comment]
> @medikoo for last one, the role is the first column, which make possible to have 1 table.

Ok so I take representation is expected to list data for each roles one after another (in first rows all data for role 1, then in following rows all data for role 2 etc.) and in first column indicate name of a role.

**Comment by vianneyl** [comment]
yes @medikoo, exactly

**Comment by medikoo** [comment]
Additional comment towards handling incomplete data and complete data:

User will be able to select periods in which some days will present incomplete data and for some days we will have it complete.
In case of _weekly_, _monthly_ and _yearly_ views, if resolution is possible only for partial time (e.g. we show February 2016, but we have data only since 15th of Feb), then we should present calculated sum of part of a period, and aside present (i) tooltip with hint that this data covers only dates since Feb 15th.

**Comment by medikoo** [comment]
@vianneyl one more question in "Roles" and "Roles / operators" tabs it looks that intention is to not provide "All Services" filtered version. Is that intentional?
e.g. in ELS we will be able to switch between "Company", "Merchant" and "Solvency" but not show results for all of them?

**Comment by vianneyl** [comment]
@medikoo ok yes we could do that if it does not bring more difficulties

thanks

2017-01-27 13:21 GMT+01:00 Mariusz Nowak <notifications@github.com>:

**Comment by medikoo** [comment]
I've split this into following tasks:
- Certificates Tab:
  - HTML view -> #1764
  - PDF generation -> #1765
  - CSV generation -> #1766
- Roles Tab:
  - HTML view -> #1767
  - PDF generation -> #1768
  - CSV generation -> #1769
- Roles / Operators Tab:
  - HTML view -> #1770
  - PDF generation -> #1771
  - CSV generation -> #1772

After all tickets are done, we can close this issue

**Comment by medikoo** [comment]
@vianneyl One more question towards first table, we still have some doubts on clarifing what exactly should be reported in those columns. Below I submit final proposal, which I feel is most logical. Please confirm whether you're ok with it:

1. __Submitted__ - How many files on this date were submitted from Part A to Part B (it's only about initial submission, we do not report here re-submission of files that were sent back)
2. __Pending__ - How many files at start of date (0:00 in system time zone) had at least one non _front-desk_ (withdrawal)  processing step (role) at _pending_ state. (File may be both _pending_ at _front desk_, but also be _pending_ at other step in such case it'll be counted here)
3. __Ready for withdraw__ - How many files on this date arrived at _front desk_ step (became ready for pickup)
5. __Withdrawn by user__ - How many files on this date were withdrawn by user (were finalzed at _front desk_ step)
6. __Rejected__ - How many files on this date got rejected (in any of steps)
7. __Sent back for corrections__ - How many files on this date got sent back to Part A (in any of steps)

Let us know

**Comment by vianneyl** [comment]
"2. pending" is for files that are pending in processing roles = not
pending in revision roles nor withdraw roles.

I am ok with the rest, the only difference I see from what I wrote is in
"1. submitted" where you would only consider the initial submission.. I am
thinking something : could you count the number of files that got
re-submitted (ie coming back from correction in Part A) ? Please only count
it, no need to display it for now in this table

thanks

2017-01-31 10:10 GMT+01:00 Mariusz Nowak <notifications@github.com>:

**Comment by medikoo** [comment]
Ok so I updated version would be:

1. __Submitted__ - How many files on this date were submitted from Part A to Part B (covers all submissions, initial and ones from sent back state)
2. __Pending__ - How many files at start of date (0:00 in system time zone) had at least one non _front-desk_ (withdrawal) and non _revision_  processing step (role) at _pending_ state. (File may be both _pending_ at _front desk/revision_, but also be _pending_ at other step that's neither of those, in such case it'll be counted here)
3. __Ready for withdraw__ - How many files on this date arrived at _front desk_ step (became ready for pickup)
5. __Withdrawn by user__ - How many files on this date were withdrawn by user (were finalzed at _front desk_ step)
6. __Rejected__ - How many files on this date got rejected (in any of steps)
7. __Sent back for corrections__ - How many files on this date got sent back to Part A (in any of steps)

@vianneyl please confirm, and one thing, we cannot make __Submitted__ like that for old records. So in case of old data (before Feb 2017) __Submitted__ will cover just initial submissions, are you OK with such inconsistency?

**Comment by vianneyl** [comment]
@medikoo if possible we could have 2 different numbers (initial submission and all the rest) so it is not inconsistent? This is what I suggested in my previous message.. If you can do so easily I would prefer, otherwise let's do it like you say.

**Comment by medikoo** [comment]
> @medikoo if possible we could have 2 different numbers (initial submission and all the rest) so it is not inconsistent? This is what I suggested in my previous message.

Sure that's not a problem, can you update UX mockup to reflect that?

**Comment by medikoo** [comment]
Or do you just want us to have that data accessible behind the scenes (that will be ensured), but stats view to show __Submitted_ as I first proposed so: _How many files on this date were submitted from Part A to Part B (it's only about initial submission, we do not count here re-submission of files that were sent back)_ ?

**Comment by medikoo** [comment]
@kamsi says that you probably didn't intend to propose any changes to __Submitted__ column, but you just wanted us to ensure that we have data about other submissions somewhere aside (that's being covered with #1757)

If that's the case, then I take that final agreement on what should be shown in table columns is:

1. __Submitted__ - How many files on this date were submitted from Part A to Part B (it's only about initial submission, we do not count here re-submission of files that were sent back)
2. __Pending__ - How many files at start of date (0:00 in system time zone) had at least one non _front-desk_ (withdrawal) and non _revision_  processing step (role) at _pending_ state. (File may be both _pending_ at _front desk/revision_, but also be _pending_ at other step that's neither of those, in such case it'll be counted here).
3. __Ready for withdraw__ - How many files on this date arrived at _front desk_ step (became ready for pickup)
5. __Withdrawn by user__ - How many files on this date were withdrawn by user (were finalzed at _front desk_ step)
6. __Rejected__ - How many files on this date got rejected (in any of steps)
7. __Sent back for corrections__ - How many files on this date got sent back to Part A (in any of steps)

No need to reply if you agree.

**Comment by vianneyl** [comment]
@medikoo yes, but please make sure that you count the number of files that
got re-submitted (ie coming back from correction in Part A), even without
showing them in the table, we might want to do something with this data one
day.

2017-01-31 10:55 GMT+01:00 Mariusz Nowak <notifications@github.com>:

**Comment by medikoo** [comment]
> @medikoo yes, but please make sure that you count the number of files that got re-submitted 

As I mentioned twice already, it will be ensured :) (t's covered at #1757)

**Comment by kamsi** [comment]
This was done long time ago, closing.
